# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6vEFQ01eKGqYJ060kR-3paRTkt1nH59
"""

# Initial Setup, Imports, and Global Configuration
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.linear_model import Perceptron as SklearnPerceptron
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo

# ----------------------------------------------------------------------------
# Global configuration
# ----------------------------------------------------------------------------
np.random.seed(42)                       # reproducibility
PLOTS_DIR = "plots"
RESULTS_DIR = "results"
os.makedirs(PLOTS_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)
sns.set_style("whitegrid")

def section(title):
    """Pretty console section header, also mirrored in the saved log."""
    bar = "=" * 78
    print(f"\n{bar}\n{title}\n{bar}")

"""# TASK 1: DATASET EXPLORATION"""

# Data Loading and Initial Exploration
section("TASK 1: DATASET EXPLORATION")

# fetch dataset
banknote_authentication = fetch_ucirepo(id=267)

# data (as pandas dataframes)
X = banknote_authentication.data.features
y = banknote_authentication.data.targets

df = pd.concat([X, y], axis=1)

print("\n--- First five samples ---")
print(df.head())

print(f"\n--- Dataset dimensions ---\nRows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\n--- Missing values per column ---")
print(df.isnull().sum())

print("\n--- Descriptive statistics ---")
desc = df.describe()
print(desc)
desc.to_csv(f"{RESULTS_DIR}/descriptive_statistics.csv")

print("\n--- Class balance ---")
print(df["class"].value_counts().rename({0: "Authentic (0)", 1: "Forged (1)"}))

"""# TASK 2: EXPLORATORY DATA ANALYSIS (EDA)"""

# EDA - Histograms and Correlation Heatmap
section("TASK 2: EXPLORATORY DATA ANALYSIS")

feature_cols = ["variance", "skewness", "curtosis", "entropy"]

# --- 2.1 Feature Histograms ---
fig, axes = plt.subplots(2, 2, figsize=(11, 8))
for ax, col in zip(axes.ravel(), feature_cols):
    sns.histplot(df[col], kde=True, ax=ax, color="steelblue")
    ax.set_title(f"Distribution of {col}")
fig.suptitle("Feature Histograms - Banknote Authentication Dataset", fontsize=14)
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/01_feature_histograms.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/01_feature_histograms.png")

# --- 2.2 Correlation Heatmap ---
fig, ax = plt.subplots(figsize=(7, 6))
corr = df[feature_cols + ["class"]].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax, square=True)
ax.set_title("Correlation Heatmap")
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/02_correlation_heatmap.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/02_correlation_heatmap.png")

import itertools

# --- 2.3 Pair Plot (class distribution for all feature pairs) ---
print("Generating pair plots for all feature combinations...")
fig = sns.pairplot(df, vars=feature_cols, hue="class", palette={0: "seagreen", 1: "indianred"}, diag_kind="kde")
fig.fig.suptitle("Pair Plots of Features by Class", y=1.02, fontsize=14)
fig.savefig(f"{PLOTS_DIR}/03_feature_pair_plots.png", dpi=150)
plt.close(fig.fig) # Corrected line: access the underlying Figure object
print(f"Saved: {PLOTS_DIR}/03_feature_pair_plots.png")

print("\nEDA Interpretation (updated for pair plots):")
print("""
- Pair Plots: Examining the grid of scatter plots reveals the relationships
  between all pairs of features, colored by class. This highlights which
  feature combinations offer better linear separability and which features
  are highly correlated. For instance, 'variance' and 'skewness' continue
  to show clear clustering, but other pairs might also reveal interesting
  patterns. The diagonal plots show kernel density estimates (KDE) for each
  feature, providing insight into their distributions per class.
""")

"""# TASK 3: DATA PREPROCESSING"""

# Data Preprocessing
section("TASK 3: DATA PREPROCESSING")

X = df[feature_cols].values
y = df["class"].values

# Normalize all numerical features (zero mean, unit variance)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Features normalized using StandardScaler (mean=0, std=1).")
print("Feature means after scaling:", np.round(X_scaled.mean(axis=0), 4))
print("Feature stds  after scaling:", np.round(X_scaled.std(axis=0), 4))

# 80/20 train-test split, stratified to preserve class balance
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTraining samples: {X_train.shape[0]}")
print(f"Testing samples : {X_test.shape[0]}")

"""# TASK 4: PERCEPTRON IMPLEMENTATION FROM SCRATCH"""

# Perceptron Implementation (Class Definition)
section("TASK 4: PERCEPTRON IMPLEMENTATION (FROM SCRATCH)")


class SingleLayerPerceptron:
    """
    A Single Layer Perceptron implemented from first principles using the
    classical Rosenblatt perceptron learning rule.

        z      = w^T x + b                 (weighted sum)
        y_hat  = step(z)                   (step activation)
        w_new  = w_old + eta * (y - y_hat) * x
        b_new  = b_old + eta * (y - y_hat)
    """

    def __init__(self, n_features, learning_rate=0.01, n_epochs=50, random_state=42):
        rng = np.random.default_rng(random_state)
        # Small random weight initialization
        self.weights = rng.normal(loc=0.0, scale=0.01, size=n_features)
        self.bias = 0.0
        self.lr = learning_rate
        self.n_epochs = n_epochs
        # History logs for Task 5 / mandatory plots
        self.history = {
            "epoch": [], "errors": [], "weights": [], "bias": [], "train_error_rate": []
        }

    @staticmethod
    def step_activation(z):
        """Step Activation Function: f(z) = 1 if z >= 0 else 0."""
        return np.where(z >= 0, 1, 0)

    def forward(self, X):
        """Forward propagation: weighted sum -> step activation."""
        z = np.dot(X, self.weights) + self.bias
        return self.step_activation(z)

    def fit(self, X, y, verbose=True):
        """Train using the perceptron learning rule, logging progress per epoch."""
        n_samples = X.shape[0]
        for epoch in range(1, self.n_epochs + 1):
            misclassified = 0
            for xi, target in zip(X, y):
                z = np.dot(xi, self.weights) + self.bias
                y_hat = self.step_activation(z)
                error = target - y_hat
                if error != 0:
                    misclassified += 1
                    self.weights += self.lr * error * xi
                    self.bias += self.lr * error

            error_rate = misclassified / n_samples
            self.history["epoch"].append(epoch)
            self.history["errors"].append(misclassified)
            self.history["weights"].append(self.weights.copy())
            self.history["bias"].append(self.bias)
            self.history["train_error_rate"].append(error_rate)

            if verbose:
                print(f"Epoch {epoch:3d} | Misclassified: {misclassified:4d} "
                      f"| Bias: {self.bias: .4f} | "
                      f"Weights: {np.round(self.weights, 4)}")

            # Early stopping once perfectly classified (converged)
            if misclassified == 0:
                if verbose:
                    print(f"Converged at epoch {epoch} (0 misclassifications).")
                break
        return self

    def predict(self, X):
        return self.forward(X)

"""# TASK 5: MODEL TRAINING"""

# Model Training and Plotting
section("TASK 5: MODEL TRAINING")

LEARNING_RATE = 0.01
N_EPOCHS = 50

n_features = X_train.shape[1]
model = SingleLayerPerceptron(n_features=n_features, learning_rate=LEARNING_RATE,
                               n_epochs=N_EPOCHS, random_state=42)
print(f"Training Single Layer Perceptron | lr={LEARNING_RATE}, epochs={N_EPOCHS}\n")
model.fit(X_train, y_train, verbose=True)

# Save epoch-wise learning table (Weight1/Weight2 as representative columns per manual template)
epoch_table = pd.DataFrame({
    "Epoch": model.history["epoch"],
    "Errors": model.history["errors"],
    "Weight_variance": [w[0] for w in model.history["weights"]],
    "Weight_skewness": [w[1] for w in model.history["weights"]],
    "Weight_curtosis": [w[2] for w in model.history["weights"]],
    "Weight_entropy": [w[3] for w in model.history["weights"]],
    "Bias": model.history["bias"],
})
epoch_table.to_csv(f"{RESULTS_DIR}/epoch_wise_learning.csv", index=False)
print(f"\nEpoch-wise learning table saved to {RESULTS_DIR}/epoch_wise_learning.csv")

# --- Mandatory Plot: Training Error vs Epoch ---
fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(model.history["epoch"], model.history["errors"], marker="o", color="crimson")
ax.set_xlabel("Epoch")
ax.set_ylabel("Misclassified Samples")
ax.set_title(f"Training Error vs Epoch (lr={LEARNING_RATE})")
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/05_training_error_vs_epoch.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/05_training_error_vs_epoch.png")

# --- Mandatory Plot: Weight Evolution ---
fig, ax = plt.subplots(figsize=(8, 5))
weight_history = np.array(model.history["weights"])
for i, col in enumerate(feature_cols):
    ax.plot(model.history["epoch"], weight_history[:, i], marker=".", label=f"w_{col}")
ax.set_xlabel("Epoch")
ax.set_ylabel("Weight Value")
ax.set_title("Weight Evolution over Training")
ax.legend()
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/06_weight_evolution.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/06_weight_evolution.png")

# --- Mandatory Plot: Bias Evolution ---
fig, ax = plt.subplots(figsize=(7, 5))
ax.plot(model.history["epoch"], model.history["bias"], marker="o", color="darkorange")
ax.set_xlabel("Epoch")
ax.set_ylabel("Bias Value")
ax.set_title("Bias Evolution over Training")
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/07_bias_evolution.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/07_bias_evolution.png")

print("\nTraining Behaviour Interpretation:")
print("""
- Training Error vs Epoch: The number of misclassified samples generally
  decreases as training progresses, indicating the perceptron is learning
  a separating hyperplane; residual oscillation (if any) suggests the data
  is not perfectly linearly separable.
- Weight Evolution: Weights change rapidly in early epochs and gradually
  stabilize, showing convergence toward a set of weights that best
  separates the two classes for a linear decision boundary.
- Bias Evolution: The bias shifts the decision boundary away from the
  origin and stabilizes alongside the weights, compensating for any
  class imbalance or offset in the feature space.
""")

"""# TASK 6: MODEL EVALUATION"""

# Model Evaluation and Plotting
section("TASK 6: MODEL EVALUATION")

y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy : {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall   : {rec:.4f}")
print(f"F1-score : {f1:.4f}")
print("\nConfusion Matrix:")
print(cm)

# --- Mandatory Plot: Confusion Matrix ---
fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=["Authentic (0)", "Forged (1)"])
disp.plot(ax=ax, cmap="Blues", colorbar=False)
ax.set_title("Confusion Matrix - Custom Perceptron")
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/08_confusion_matrix.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/08_confusion_matrix.png")

tn, fp, fn, tp = cm.ravel()
print(f"\nTP={tp}, FP={fp}, TN={tn}, FN={fn}")
print("""
Interpretation: TP and TN represent correctly classified forged and
authentic notes respectively. Any FP means an authentic note was wrongly
flagged as forged, while FN means a forged note slipped through as
authentic (the more costly error in a real-world banknote-authentication
system).
""")

"""# TASK 7 / ADDITIONAL TASK 3: LEARNING RATE COMPARISON & DECISION BOUNDARY (OPTIONAL)"""

# Learning Rate Comparison & Decision Boundary Plot
section("TASK 7 / ADDITIONAL TASK 3: LEARNING RATE COMPARISON")

learning_rates = [0.001, 0.01, 0.1]
lr_results = []
lr_histories = {}

for lr in learning_rates:
    m = SingleLayerPerceptron(n_features=n_features, learning_rate=lr,
                               n_epochs=N_EPOCHS, random_state=42)
    m.fit(X_train, y_train, verbose=False)
    preds = m.predict(X_test)
    lr_results.append({
        "Learning Rate": lr,
        "Epochs to Converge": m.history["epoch"][-1],
        "Final Train Errors": m.history["errors"][-1],
        "Test Accuracy": accuracy_score(y_test, preds),
        "Test F1-score": f1_score(y_test, preds, zero_division=0),
    })
    lr_histories[lr] = m.history

lr_df = pd.DataFrame(lr_results)
print(lr_df.to_string(index=False))
lr_df.to_csv(f"{RESULTS_DIR}/learning_rate_comparison.csv", index=False)

# --- Mandatory Plot: Learning Rate Comparison ---
fig, ax = plt.subplots(figsize=(8, 5))
for lr in learning_rates:
    h = lr_histories[lr]
    ax.plot(h["epoch"], h["errors"], marker=".", label=f"lr={lr}")
ax.set_xlabel("Epoch")
ax.set_ylabel("Misclassified Samples")
ax.set_title("Learning Rate Comparison - Convergence Behaviour")
ax.legend()
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/09_learning_rate_comparison.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/09_learning_rate_comparison.png")

print("""
Interpretation: For a linear model like the perceptron, the learning rate
mainly affects the size of each weight-update step rather than whether
convergence happens at all. A very small learning rate (0.001) updates
weights cautiously and may need more epochs to reach a stable boundary.
A moderate rate (0.01) typically converges smoothly. A larger rate (0.1)
can converge faster but may oscillate more if the classes are not
perfectly linearly separable, since large corrective steps can overshoot
the optimal boundary.
""")

# ==============================================================================
# DECISION BOUNDARY (OPTIONAL MANDATORY PLOT)
# Trained on two selected features only: variance & skewness
# ==============================================================================
section("DECISION BOUNDARY (OPTIONAL PLOT)")

X_2d = X_scaled[:, :2]  # variance, skewness
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X_2d, y, test_size=0.2, random_state=42, stratify=y
)
model_2d = SingleLayerPerceptron(n_features=2, learning_rate=0.01,
                                  n_epochs=N_EPOCHS, random_state=42)
model_2d.fit(X2_train, y2_train, verbose=False)

fig, ax = plt.subplots(figsize=(7, 6))
x_min, x_max = X_2d[:, 0].min() - 1, X_2d[:, 0].max() + 1
y_min, y_max = X_2d[:, 1].min() - 1, X_2d[:, 1].max() + 1
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 300), np.linspace(y_min, y_max, 300))
grid_preds = model_2d.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

ax.contourf(xx, yy, grid_preds, alpha=0.25, cmap="RdYlGn_r")
sns.scatterplot(x=X_2d[:, 0], y=X_2d[:, 1], hue=y,
                 palette={0: "seagreen", 1: "indianred"}, alpha=0.8, ax=ax)
ax.set_xlabel("variance (scaled)")
ax.set_ylabel("skewness (scaled)")
ax.set_title("Decision Boundary (Perceptron trained on variance & skewness)")
ax.legend(title="Class", labels=["Authentic (0)", "Forged (1)"])
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/10_decision_boundary.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/10_decision_boundary.png")
print("""
Interpretation: The shaded regions show how the perceptron partitions the
2-feature space with a straight line (hyperplane in 2D). Most points fall
on the correct side, visually confirming that variance and skewness alone
already carry substantial class-separating information.
""")

"""# ADDITIONAL TASKS AND SUMMARY"""

# Additional Tasks and Performance Summary

# ==============================================================================
# ADDITIONAL TASK 2: COMPARISON WITH SCIKIT-LEARN'S PERCEPTRON
# ==============================================================================
section("ADDITIONAL TASK 2: COMPARISON WITH SCIKIT-LEARN'S PERCEPTRON")

sk_model = SklearnPerceptron(eta0=LEARNING_RATE, max_iter=N_EPOCHS,
                              tol=1e-3, random_state=42)
sk_model.fit(X_train, y_train)
sk_pred = sk_model.predict(X_test)

comparison_df = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score"],
    "Custom Perceptron": [
        acc, prec, rec, f1
    ],
    "Scikit-learn Perceptron": [
        accuracy_score(y_test, sk_pred),
        precision_score(y_test, sk_pred, zero_division=0),
        recall_score(y_test, sk_pred, zero_division=0),
        f1_score(y_test, sk_pred, zero_division=0),
    ],
})
print(comparison_df.to_string(index=False))
comparison_df.to_csv(f"{RESULTS_DIR}/sklearn_comparison.csv", index=False)

print("""
Interpretation: The custom from-scratch perceptron and scikit-learn's
Perceptron implement the same underlying learning rule, so their metrics
are typically very close. Minor differences arise from details such as
weight initialization, shuffling of samples between epochs, and internal
stopping criteria used by scikit-learn.
""")


# ==============================================================================
# ADDITIONAL TASK 1: STEP vs SIGMOID ACTIVATION - DISCUSSION
# ==============================================================================
section("ADDITIONAL TASK 1: STEP vs SIGMOID ACTIVATION FUNCTION")

discussion_step_vs_sigmoid = """
Step Activation:
  f(z) = 1 if z >= 0 else 0
  - Output is discrete (0 or 1), with a discontinuous jump at z = 0.
  - Derivative is 0 everywhere except undefined at z = 0, so gradient
    descent / backpropagation cannot use it to compute meaningful
    weight updates in deeper, multi-layer networks.
  - Only usable with the simple perceptron learning rule shown above,
    which relies directly on the (target - prediction) error, not on
    calculus-based gradients.

Sigmoid Activation:
  f(z) = 1 / (1 + e^-z)
  - Output is continuous in (0, 1) and smoothly differentiable
    everywhere, giving a well-defined, non-zero gradient almost
    everywhere.
  - This differentiability is essential for backpropagation, which
    needs to propagate gradients of the loss function through every
    layer using the chain rule.
  - Continuous outputs can also be interpreted as class probabilities,
    which is useful for probabilistic decision-making and computing
    smooth loss functions such as binary cross-entropy.

Why modern deep learning avoids the Step function:
  1. Non-differentiability makes gradient-based optimization (SGD, Adam,
     etc.) impossible to apply directly.
  2. Zero gradient almost everywhere means no learning signal can flow
     backward through a stack of layers ("no gradient to propagate").
  3. Networks with step activations cannot represent smooth, complex
     decision surfaces the way sigmoid/tanh/ReLU-based deep networks can.
  Because of this, the Step function is retained only for pedagogical
  study of the classical Rosenblatt perceptron, while Sigmoid, Tanh,
  ReLU, Leaky ReLU, and Softmax are used in practice.
"""
print(discussion_step_vs_sigmoid)
with open(f"{RESULTS_DIR}/additional_task1_step_vs_sigmoid.txt", "w") as f:
    f.write(discussion_step_vs_sigmoid)


# ==============================================================================
# ADDITIONAL TASK 4: WHY A SINGLE LAYER PERCEPTRON CANNOT SOLVE XOR
# ==============================================================================
section("ADDITIONAL TASK 4: WHY SLP CANNOT SOLVE XOR")

xor_discussion = """
The XOR function is defined as:
  (0,0) -> 0   (0,1) -> 1   (1,0) -> 1   (1,1) -> 0

A Single Layer Perceptron can only compute a single linear decision
boundary: it separates the input space into two regions using one
straight line (or hyperplane in higher dimensions), of the form
w1*x1 + w2*x2 + b = 0.

Plotting the four XOR points shows that the two output classes (0 and 1)
are diagonally opposite one another - no single straight line can group
{(0,0),(1,1)} on one side and {(0,1),(1,0)} on the other. This makes XOR
a classic example of a "not linearly separable" problem.

Because the perceptron's decision function is fundamentally linear, it
cannot represent this pattern regardless of how the weights and bias are
tuned or how long it is trained; the learning rule will simply keep
oscillating and never converge to zero error. Solving XOR requires at
least one hidden layer with a non-linear activation function (a
Multilayer Perceptron / MLP), which can combine two linear boundaries to
carve out the required non-linear region.
"""
print(xor_discussion)
with open(f"{RESULTS_DIR}/additional_task4_xor_explanation.txt", "w") as f:
    f.write(xor_discussion)

# quick demonstration: try to train the perceptron on XOR itself
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([0, 1, 1, 0])
xor_model = SingleLayerPerceptron(n_features=2, learning_rate=0.1, n_epochs=20, random_state=42)
xor_model.fit(X_xor, y_xor, verbose=False)
xor_pred = xor_model.predict(X_xor)
print(f"XOR demo -> targets: {y_xor}, perceptron predictions: {xor_pred}, "
      f"final train errors: {xor_model.history['errors'][-1]} "
      f"(never reaches 0 across epochs, confirming non-convergence).")


# ==============================================================================
# ADDITIONAL TASK 5: EFFECT OF FEATURE NORMALIZATION ON CONVERGENCE
# ==============================================================================
section("ADDITIONAL TASK 5: EFFECT OF NORMALIZATION ON CONVERGENCE")

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model_raw = SingleLayerPerceptron(n_features=n_features, learning_rate=LEARNING_RATE,
                                   n_epochs=N_EPOCHS, random_state=42)
model_raw.fit(X_train_raw, y_train_raw, verbose=False)
pred_raw = model_raw.predict(X_test_raw)

norm_compare = pd.DataFrame({
    "Setup": ["Without Normalization", "With Normalization (StandardScaler)"],
    "Epochs Run": [model_raw.history["epoch"][-1], model.history["epoch"][-1]],
    "Final Train Errors": [model_raw.history["errors"][-1], model.history["errors"][-1]],
    "Test Accuracy": [accuracy_score(y_test_raw, pred_raw), acc],
})
print(norm_compare.to_string(index=False))
norm_compare.to_csv(f"{RESULTS_DIR}/normalization_effect.csv", index=False)

print("""
Interpretation: Without normalization, raw features have very different
scales and ranges, which can make the weighted sum (and therefore the
learning updates) dominated by whichever feature has the largest
magnitude, slowing or destabilizing convergence. After normalization
(zero mean, unit variance), all features contribute more evenly to the
weighted sum, typically leading to faster and more stable convergence
and comparable-or-better test accuracy.
"""
)


# ==============================================================================
# PERFORMANCE / TRAINING SUMMARY TABLE
# ==============================================================================
section("PERFORMANCE TABLES")

training_summary = pd.DataFrame({
    "Metric": [
        "Dataset Size", "Train/Test Split", "Learning Rate", "Epochs Run",
        "Final Weights", "Final Bias", "Accuracy", "Precision", "Recall", "F1-score"
    ],
    "Value": [
        len(df), "80% / 20%", LEARNING_RATE, model.history["epoch"][-1],
        np.round(model.weights, 4).tolist(), round(model.bias, 4),
        round(acc, 4), round(prec, 4), round(rec, 4), round(f1, 4)
    ]
})
print(training_summary.to_string(index=False))
training_summary.to_csv(f"{RESULTS_DIR}/training_summary.csv", index=False)

print(f"\nAll result tables saved under ./{RESULTS_DIR}/")
print(f"All plots saved under ./{PLOTS_DIR}/")
print("\nExperiment 1 complete.")

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, ConfusionMatrixDisplay
)
from sklearn.linear_model import Perceptron as SklearnPerceptron
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo

# ----------------------------------------------------------------------------
# Global configuration
# ----------------------------------------------------------------------------
np.random.seed(42)                       # reproducibility
PLOTS_DIR = "plots"
RESULTS_DIR = "results"
os.makedirs(PLOTS_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)
sns.set_style("whitegrid")

def section(title):
    """Pretty console section header, also mirrored in the saved log."""
    bar = "=" * 78
    print(f"\n{bar}\n{title}\n{bar}")


# ==============================================================================
# TASK 1: DATASET EXPLORATION
# ==============================================================================
section("TASK 1: DATASET EXPLORATION")

# fetch dataset
banknote_authentication = fetch_ucirepo(id=267)

# data (as pandas dataframes)
X = banknote_authentication.data.features
y = banknote_authentication.data.targets

df = pd.concat([X, y], axis=1)

print("\n--- First five samples ---")
print(df.head())

print(f"\n--- Dataset dimensions ---\nRows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\n--- Missing values per column ---")
print(df.isnull().sum())

print("\n--- Descriptive statistics ---")
desc = df.describe()
print(desc)
desc.to_csv(f"{RESULTS_DIR}/descriptive_statistics.csv")

print("\n--- Class balance ---")
print(df["class"].value_counts().rename({0: "Authentic (0)", 1: "Forged (1)"}))


# ==============================================================================
# TASK 2: EXPLORATORY DATA ANALYSIS (EDA)
# ==============================================================================
section("TASK 2: EXPLORATORY DATA ANALYSIS")

feature_cols = ["variance", "skewness", "curtosis", "entropy"]

# --- 2.1 Feature Histograms ---
fig, axes = plt.subplots(2, 2, figsize=(11, 8))
for ax, col in zip(axes.ravel(), feature_cols):
    sns.histplot(df[col], kde=True, ax=ax, color="steelblue")
    ax.set_title(f"Distribution of {col}")
fig.suptitle("Feature Histograms - Banknote Authentication Dataset", fontsize=14)
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/01_feature_histograms.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/01_feature_histograms.png")

# --- 2.2 Correlation Heatmap ---
fig, ax = plt.subplots(figsize=(7, 6))
corr = df[feature_cols + ["class"]].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", ax=ax, square=True)
ax.set_title("Correlation Heatmap")
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/02_correlation_heatmap.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/02_correlation_heatmap.png")

# --- 2.3 Scatter Plot (class distribution using two most informative features) ---
fig, ax = plt.subplots(figsize=(7, 6))
sns.scatterplot(data=df, x="variance", y="skewness", hue="class",
                 palette={0: "seagreen", 1: "indianred"}, alpha=0.7, ax=ax)
ax.set_title("Class Distribution: Variance vs Skewness")
ax.legend(title="Class", labels=["Authentic (0)", "Forged (1)"])
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/03_scatter_plot.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/03_scatter_plot.png")

# --- 2.4 Boxplots ---
fig, axes = plt.subplots(2, 2, figsize=(11, 8))
for ax, col in zip(axes.ravel(), feature_cols):
    sns.boxplot(data=df, x="class", y=col, hue="class",
                palette={0: "seagreen", 1: "indianred"}, legend=False, ax=ax)
    ax.set_title(f"{col} by Class")
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["Authentic (0)", "Forged (1)"])
fig.suptitle("Boxplots of Features by Class", fontsize=14)
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/04_boxplots.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/04_boxplots.png")

print("\nEDA Interpretation:")
print("""
- Histograms: 'variance' and 'skewness' show fairly spread, roughly
  bimodal distributions (reflecting the two classes), while 'curtosis' and
  'entropy' are more concentrated with some skew/outliers.
- Correlation Heatmap: 'variance' has the strongest negative correlation
  with the class label, meaning it is likely the most discriminative single
  feature. 'skewness' and 'curtosis' are also noticeably correlated with
  each other.
- Scatter Plot: Using variance and skewness, authentic and forged notes
  form two visually distinguishable clusters with some overlap, suggesting
  the classes are close to (but not perfectly) linearly separable.
- Boxplots: Authentic notes (0) tend to have higher 'variance' and
  'skewness' values with tighter spread, while forged notes (1) show lower
  medians and more outliers, especially in 'curtosis' and 'entropy'.
""")


# ==============================================================================
# TASK 3: DATA PREPROCESSING
# ==============================================================================
section("TASK 3: DATA PREPROCESSING")

X = df[feature_cols].values
y = df["class"].values

# Normalize all numerical features (zero mean, unit variance)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Features normalized using StandardScaler (mean=0, std=1).")
print("Feature means after scaling:", np.round(X_scaled.mean(axis=0), 4))
print("Feature stds  after scaling:", np.round(X_scaled.std(axis=0), 4))

# 80/20 train-test split, stratified to preserve class balance
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)
print(f"\nTraining samples: {X_train.shape[0]}")
print(f"Testing samples : {X_test.shape[0]}")


# ==============================================================================
# TASK 4: PERCEPTRON IMPLEMENTATION FROM SCRATCH
# ==============================================================================
section("TASK 4: PERCEPTRON IMPLEMENTATION (FROM SCRATCH)")


class SingleLayerPerceptron:
    """
    A Single Layer Perceptron implemented from first principles using the
    classical Rosenblatt perceptron learning rule.

        z      = w^T x + b                 (weighted sum)
        y_hat  = step(z)                   (step activation)
        w_new  = w_old + eta * (y - y_hat) * x
        b_new  = b_old + eta * (y - y_hat)
    """

    def __init__(self, n_features, learning_rate=0.01, n_epochs=50, random_state=42):
        rng = np.random.default_rng(random_state)
        # Small random weight initialization
        self.weights = rng.normal(loc=0.0, scale=0.01, size=n_features)
        self.bias = 0.0
        self.lr = learning_rate
        self.n_epochs = n_epochs
        # History logs for Task 5 / mandatory plots
        self.history = {
            "epoch": [], "errors": [], "weights": [], "bias": [], "train_error_rate": []
        }

    @staticmethod
    def step_activation(z):
        """Step Activation Function: f(z) = 1 if z >= 0 else 0."""
        return np.where(z >= 0, 1, 0)

    def forward(self, X):
        """Forward propagation: weighted sum -> step activation."""
        z = np.dot(X, self.weights) + self.bias
        return self.step_activation(z)

    def fit(self, X, y, verbose=True):
        """Train using the perceptron learning rule, logging progress per epoch."""
        n_samples = X.shape[0]
        for epoch in range(1, self.n_epochs + 1):
            misclassified = 0
            for xi, target in zip(X, y):
                z = np.dot(xi, self.weights) + self.bias
                y_hat = self.step_activation(z)
                error = target - y_hat
                if error != 0:
                    misclassified += 1
                    self.weights += self.lr * error * xi
                    self.bias += self.lr * error

            error_rate = misclassified / n_samples
            self.history["epoch"].append(epoch)
            self.history["errors"].append(misclassified)
            self.history["weights"].append(self.weights.copy())
            self.history["bias"].append(self.bias)
            self.history["train_error_rate"].append(error_rate)

            if verbose:
                print(f"Epoch {epoch:3d} | Misclassified: {misclassified:4d} "
                      f"| Bias: {self.bias: .4f} | "
                      f"Weights: {np.round(self.weights, 4)}")

            # Early stopping once perfectly classified (converged)
            if misclassified == 0:
                if verbose:
                    print(f"Converged at epoch {epoch} (0 misclassifications).")
                break
        return self

    def predict(self, X):
        return self.forward(X)


# ==============================================================================
# TASK 5: MODEL TRAINING
# ==============================================================================
section("TASK 5: MODEL TRAINING")

LEARNING_RATE = 0.01
N_EPOCHS = 50

n_features = X_train.shape[1]
model = SingleLayerPerceptron(n_features=n_features, learning_rate=LEARNING_RATE,
                               n_epochs=N_EPOCHS, random_state=42)
print(f"Training Single Layer Perceptron | lr={LEARNING_RATE}, epochs={N_EPOCHS}\n")
model.fit(X_train, y_train, verbose=True)

# Save epoch-wise learning table (Weight1/Weight2 as representative columns per manual template)
epoch_table = pd.DataFrame({
    "Epoch": model.history["epoch"],
    "Errors": model.history["errors"],
    "Weight_variance": [w[0] for w in model.history["weights"]],
    "Weight_skewness": [w[1] for w in model.history["weights"]],
    "Weight_curtosis": [w[2] for w in model.history["weights"]],
    "Weight_entropy": [w[3] for w in model.history["weights"]],
    "Bias": model.history["bias"],
})
epoch_table.to_csv(f"{RESULTS_DIR}/epoch_wise_learning.csv", index=False)
print(f"\nEpoch-wise learning table saved to {RESULTS_DIR}/epoch_wise_learning.csv")

# --- Training Behaviour Interpretation (for single LR model) ---
print("\nTraining Behaviour Interpretation:")
print("""
- Training Error vs Epoch: The number of misclassified samples generally
  decreases as training progresses, indicating the perceptron is learning
  a separating hyperplane; residual oscillation (if any) suggests the data
  is not perfectly linearly separable.
- Weight Evolution: Weights change rapidly in early epochs and gradually
  stabilize, showing convergence toward a set of weights that best
  separates the two classes for a linear decision boundary.
- Bias Evolution: The bias shifts the decision boundary away from the
  origin and stabilizes alongside the weights, compensating for any
  class imbalance or offset in the feature space.
""")


# ==============================================================================
# TASK 6: MODEL EVALUATION
# ==============================================================================
section("TASK 6: MODEL EVALUATION")

y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, zero_division=0)
rec = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy : {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall   : {rec:.4f}")
print(f"F1-score : {f1:.4f}")
print("\nConfusion Matrix:")
print(cm)

# --- Mandatory Plot: Confusion Matrix ---
fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                               display_labels=["Authentic (0)", "Forged (1)"])
disp.plot(ax=ax, cmap="Blues", colorbar=False)
ax.set_title("Confusion Matrix - Custom Perceptron")
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/08_confusion_matrix.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/08_confusion_matrix.png")

tn, fp, fn, tp = cm.ravel()
print(f"\nTP={tp}, FP={fp}, TN={tn}, FN={fn}")
print("""
Interpretation: TP and TN represent correctly classified forged and
authentic notes respectively. Any FP means an authentic note was wrongly
flagged as forged, while FN means a forged note slipped through as
authentic (the more costly error in a real-world banknote-authentication
system).
""")


# ==============================================================================
# TASK 7: EFFECT OF DIFFERENT LEARNING RATES
# (also fulfils Additional Task 3: repeat with lr = 0.001, 0.01, 0.1)
# ==============================================================================
section("TASK 7 / ADDITIONAL TASK 3: LEARNING RATE COMPARISON")

learning_rates = [0.001, 0.01, 0.1]
lr_results = []
lr_histories = {}

for lr in learning_rates:
    m = SingleLayerPerceptron(n_features=n_features, learning_rate=lr,
                               n_epochs=N_EPOCHS, random_state=42)
    m.fit(X_train, y_train, verbose=False)
    preds = m.predict(X_test)
    lr_results.append({
        "Learning Rate": lr,
        "Epochs to Converge": m.history["epoch"][-1],
        "Final Train Errors": m.history["errors"][-1],
        "Test Accuracy": accuracy_score(y_test, preds),
        "Test F1-score": f1_score(y_test, preds, zero_division=0),
    })
    lr_histories[lr] = m.history

lr_df = pd.DataFrame(lr_results)
print(lr_df.to_string(index=False))
lr_df.to_csv(f"{RESULTS_DIR}/learning_rate_comparison.csv", index=False)

# --- Combined Plot: Training Error, Weight, and Bias Evolution (All Learning Rates) ---
fig, axes = plt.subplots(3, 1, figsize=(10, 15), sharex=True)
fig.suptitle('Evolution of Training Metrics Across Learning Rates', fontsize=16)

# Subplot 1: Training Error vs Epoch
ax1 = axes[0]
for lr_val in learning_rates:
    h = lr_histories[lr_val]
    ax1.plot(h["epoch"], h["errors"], marker=".", label=f"lr={lr_val}")
ax1.set_ylabel("Misclassified Samples")
ax1.set_title("Training Error vs Epoch")
ax1.legend()

# Subplot 2: Weight Evolution
ax2 = axes[1]
colors = plt.cm.viridis(np.linspace(0, 1, len(feature_cols)))
for lr_val, history in lr_histories.items():
    weight_history = np.array(history["weights"])
    for i, col in enumerate(feature_cols):
        ax2.plot(history["epoch"], weight_history[:, i], linestyle='--', color=colors[i], label=f"w_{col} (lr={lr_val})")
ax2.set_ylabel("Weight Value")
ax2.set_title("Weight Evolution over Training")
# Adjust legend to avoid clutter, perhaps place outside if too many items
# ax2.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
ax2.legend(loc='center left', bbox_to_anchor=(1, 0.5))

# Subplot 3: Bias Evolution
ax3 = axes[2]
for lr_val, history in lr_histories.items():
    ax3.plot(history["epoch"], history["bias"], marker=".", label=f"Bias (lr={lr_val})")
ax3.set_xlabel("Epoch")
ax3.set_ylabel("Bias Value")
ax3.set_title("Bias Evolution over Training")
ax3.legend()

fig.tight_layout(rect=[0, 0.03, 0.9, 0.98]) # Adjust layout to prevent suptitle overlap
fig.savefig(f"{PLOTS_DIR}/05_06_07_combined_evolutions_all_lrs.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/05_06_07_combined_evolutions_all_lrs.png")

print("""
Interpretation: For a linear model like the perceptron, the learning rate
mainly affects the size of each weight-update step rather than whether
convergence happens at all. A very small learning rate (0.001) updates
weights cautiously and may need more epochs to reach a stable boundary.
A moderate rate (0.01) typically converges smoothly. A larger rate (0.1)
can converge faster but may oscillate more if the classes are not
perfectly linearly separable, since large corrective steps can overshoot
the optimal boundary.
""")


# ==============================================================================
# DECISION BOUNDARY (OPTIONAL MANDATORY PLOT)
# Trained on two selected features only: variance & skewness
# ==============================================================================
section("DECISION BOUNDARY (OPTIONAL PLOT)")

X_2d = X_scaled[:, :2]  # variance, skewness
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X_2d, y, test_size=0.2, random_state=42, stratify=y
)
model_2d = SingleLayerPerceptron(n_features=2, learning_rate=0.01,
                                  n_epochs=N_EPOCHS, random_state=42)
model_2d.fit(X2_train, y2_train, verbose=False)

fig, ax = plt.subplots(figsize=(7, 6))
x_min, x_max = X_2d[:, 0].min() - 1, X_2d[:, 0].max() + 1
y_min, y_max = X_2d[:, 1].min() - 1, X_2d[:, 1].max() + 1
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 300), np.linspace(y_min, y_max, 300))
grid_preds = model_2d.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

ax.contourf(xx, yy, grid_preds, alpha=0.25, cmap="RdYlGn_r")
sns.scatterplot(x=X_2d[:, 0], y=X_2d[:, 1], hue=y,
                 palette={0: "seagreen", 1: "indianred"}, alpha=0.8, ax=ax)
ax.set_xlabel("variance (scaled)")
ax.set_ylabel("skewness (scaled)")
ax.set_title("Decision Boundary (Perceptron trained on variance & skewness)")
ax.legend(title="Class", labels=["Authentic (0)", "Forged (1)"])
fig.tight_layout()
fig.savefig(f"{PLOTS_DIR}/10_decision_boundary.png", dpi=150)
plt.close(fig)
print(f"Saved: {PLOTS_DIR}/10_decision_boundary.png")
print("""
Interpretation: The shaded regions show how the perceptron partitions the
2-feature space with a straight line (hyperplane in 2D). Most points fall
on the correct side, visually confirming that variance and skewness alone
already carry substantial class-separating information.
""")


# ==============================================================================
# ADDITIONAL TASK 2: COMPARISON WITH SCIKIT-LEARN'S PERCEPTRON
# ==============================================================================
section("ADDITIONAL TASK 2: COMPARISON WITH SCIKIT-LEARN'S PERCEPTRON")

sk_model = SklearnPerceptron(eta0=LEARNING_RATE, max_iter=N_EPOCHS,
                              tol=1e-3, random_state=42)
sk_model.fit(X_train, y_train)
sk_pred = sk_model.predict(X_test)

comparison_df = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-score"],
    "Custom Perceptron": [
        acc, prec, rec, f1
    ],
    "Scikit-learn Perceptron": [
        accuracy_score(y_test, sk_pred),
        precision_score(y_test, sk_pred, zero_division=0),
        recall_score(y_test, sk_pred, zero_division=0),
        f1_score(y_test, sk_pred, zero_division=0),
    ],
})
print(comparison_df.to_string(index=False))
comparison_df.to_csv(f"{RESULTS_DIR}/sklearn_comparison.csv", index=False)

print("""
Interpretation: The custom from-scratch perceptron and scikit-learn's
Perceptron implement the same underlying learning rule, so their metrics
are typically very close. Minor differences arise from details such as
weight initialization, shuffling of samples between epochs, and internal
stopping criteria used by scikit-learn.
""")


# ==============================================================================
# ADDITIONAL TASK 1: STEP vs SIGMOID ACTIVATION - DISCUSSION
# ==============================================================================
section("ADDITIONAL TASK 1: STEP vs SIGMOID ACTIVATION FUNCTION")

discussion_step_vs_sigmoid = """
Step Activation:
  f(z) = 1 if z >= 0 else 0
  - Output is discrete (0 or 1), with a discontinuous jump at z = 0.
  - Derivative is 0 everywhere except undefined at z = 0, so gradient
    descent / backpropagation cannot use it to compute meaningful
    weight updates in deeper, multi-layer networks.
  - Only usable with the simple perceptron learning rule shown above,
    which relies directly on the (target - prediction) error, not on
    calculus-based gradients.

Sigmoid Activation:
  f(z) = 1 / (1 + e^-z)
  - Output is continuous in (0, 1) and smoothly differentiable
    everywhere, giving a well-defined, non-zero gradient almost
    everywhere.
  - This differentiability is essential for backpropagation, which
    needs to propagate gradients of the loss function through every
    layer using the chain rule.
  - Continuous outputs can also be interpreted as class probabilities,
    which is useful for probabilistic decision-making and computing
    smooth loss functions such as binary cross-entropy.

Why modern deep learning avoids the Step function:
  1. Non-differentiability makes gradient-based optimization (SGD, Adam,
     etc.) impossible to apply directly.
  2. Zero gradient almost everywhere means no learning signal can flow
     backward through a stack of layers ("no gradient to propagate").
  3. Networks with step activations cannot represent smooth, complex
     decision surfaces the way sigmoid/tanh/ReLU-based deep networks can.
  Because of this, the Step function is retained only for pedagogical
  study of the classical Rosenblatt perceptron, while Sigmoid, Tanh,
  ReLU, Leaky ReLU, and Softmax are used in practice.
"""
print(discussion_step_vs_sigmoid)
with open(f"{RESULTS_DIR}/additional_task1_step_vs_sigmoid.txt", "w") as f:
    f.write(discussion_step_vs_sigmoid)


# ==============================================================================
# ADDITIONAL TASK 4: WHY A SINGLE LAYER PERCEPTRON CANNOT SOLVE XOR
# ==============================================================================
section("ADDITIONAL TASK 4: WHY SLP CANNOT SOLVE XOR")

xor_discussion = """
The XOR function is defined as:
  (0,0) -> 0   (0,1) -> 1   (1,0) -> 1   (1,1) -> 0

A Single Layer Perceptron can only compute a single linear decision
boundary: it separates the input space into two regions using one
straight line (or hyperplane in higher dimensions), of the form
w1*x1 + w2*x2 + b = 0.

Plotting the four XOR points shows that the two output classes (0 and 1)
are diagonally opposite one another - no single straight line can group
{(0,0),(1,1)} on one side and {(0,1),(1,0)} on the other. This makes XOR
a classic example of a "not linearly separable" problem.

Because the perceptron's decision function is fundamentally linear, it
cannot represent this pattern regardless of how the weights and bias are
tuned or how long it is trained; the learning rule will simply keep
oscillating and never converge to zero error. Solving XOR requires at
least one hidden layer with a non-linear activation function (a
Multilayer Perceptron / MLP), which can combine two linear boundaries to
carve out the required non-linear region.
"""
print(xor_discussion)
with open(f"{RESULTS_DIR}/additional_task4_xor_explanation.txt", "w") as f:
    f.write(xor_discussion)

# quick demonstration: try to train the perceptron on XOR itself
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([0, 1, 1, 0])
xor_model = SingleLayerPerceptron(n_features=2, learning_rate=0.1, n_epochs=20, random_state=42)
xor_model.fit(X_xor, y_xor, verbose=False)
xor_pred = xor_model.predict(X_xor)
print(f"XOR demo -> targets: {y_xor}, perceptron predictions: {xor_pred}, "
      f"final train errors: {xor_model.history['errors'][-1]} "
      f"(never reaches 0 across epochs, confirming non-convergence).")


# ==============================================================================
# ADDITIONAL TASK 5: EFFECT OF FEATURE NORMALIZATION ON CONVERGENCE
# ==============================================================================
section("ADDITIONAL TASK 5: EFFECT OF NORMALIZATION ON CONVERGENCE")

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model_raw = SingleLayerPerceptron(n_features=n_features, learning_rate=LEARNING_RATE,
                                   n_epochs=N_EPOCHS, random_state=42)
model_raw.fit(X_train_raw, y_train_raw, verbose=False)
pred_raw = model_raw.predict(X_test_raw)

norm_compare = pd.DataFrame({
    "Setup": ["Without Normalization", "With Normalization (StandardScaler)"],
    "Epochs Run": [model_raw.history["epoch"][-1], model.history["epoch"][-1]],
    "Final Train Errors": [model_raw.history["errors"][-1], model.history["errors"][-1]],
    "Test Accuracy": [accuracy_score(y_test_raw, pred_raw), acc],
})
print(norm_compare.to_string(index=False))
norm_compare.to_csv(f"{RESULTS_DIR}/normalization_effect.csv", index=False)

print("""
Interpretation: Without normalization, raw features have very different
scales and ranges, which can make the weighted sum (and therefore the
learning updates) dominated by whichever feature has the largest
magnitude, slowing or destabilizing convergence. After normalization
(zero mean, unit variance), all features contribute more evenly to the
weighted sum, typically leading to faster and more stable convergence
and comparable-or-better test accuracy.
"""
)


# ==============================================================================
# PERFORMANCE / TRAINING SUMMARY TABLE
# ==============================================================================
section("PERFORMANCE TABLES")

training_summary = pd.DataFrame({
    "Metric": [
        "Dataset Size", "Train/Test Split", "Learning Rate", "Epochs Run",
        "Final Weights", "Final Bias", "Accuracy", "Precision", "Recall", "F1-score"
    ],
    "Value": [
        len(df), "80% / 20%", LEARNING_RATE, model.history["epoch"][-1],
        np.round(model.weights, 4).tolist(), round(model.bias, 4),
        round(acc, 4), round(prec, 4), round(rec, 4), round(f1, 4)
    ]
})
print(training_summary.to_string(index=False))
training_summary.to_csv(f"{RESULTS_DIR}/training_summary.csv", index=False)

print(f"\nAll result tables saved under ./{RESULTS_DIR}/")
print(f"All plots saved under ./{PLOTS_DIR}/")
print("\nExperiment 1 complete.")