# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Gnz6Fw-yrOaWbNzOHXerk0WDDIz5tHT
"""

!pip install -U scikit-learn==1.5.2

"""## Task 1: Dataset Exploration"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

# Load the Fashion-MNIST dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

print(f"Training data shape: {x_train.shape}")
print(f"Training labels shape: {y_train.shape}")
print(f"Testing data shape: {x_test.shape}")
print(f"Testing labels shape: {y_test.shape}")

"""### Displaying Sample Images"""

# Define class names for Fashion-MNIST
class_names = [
    'T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
    'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot'
]

plt.figure(figsize=(10, 10))
for i in range(10):
    plt.subplot(5, 5, i + 1) # Adjust subplot grid to 5x5 if more images are needed, or 2x5 for 10 images
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(x_train[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[y_train[i]])
plt.suptitle('Sample Fashion-MNIST Images', y=1.02, fontsize=16) # Add a suptitle for the entire figure
plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout to prevent suptitle overlap
plt.show()

"""### Plotting Class Distribution"""

# Calculate class distribution
unique, counts = np.unique(y_train, return_counts=True)
plt.figure(figsize=(10, 6))
plt.bar(class_names, counts)
plt.xticks(rotation=45, ha='right')
plt.xlabel('Class')
plt.ylabel('Number of Images')
plt.title('Fashion-MNIST Training Data Class Distribution')
plt.tight_layout()
plt.show()

"""## Task 2: Data Preprocessing"""

print(f"Original training data shape: {x_train.shape}")
print(f"Original testing data shape: {x_test.shape}")

# 1. Flatten images
# Each image is 28x28 pixels. Flattening converts it to a 1D array of 784 pixels.
x_train_flat = x_train.reshape(-1, 28 * 28)
x_test_flat = x_test.reshape(-1, 28 * 28)

print(f"Flattened training data shape: {x_train_flat.shape}")
print(f"Flattened testing data shape: {x_test_flat.shape}")

# 2. Normalize pixel values to [0, 1]
x_train_norm = x_train_flat.astype('float32') / 255.0
x_test_norm = x_test_flat.astype('float32') / 255.0

print(f"Normalized training data shape: {x_train_norm.shape}")
print(f"Normalized testing data shape: {x_test_norm.shape}")

# 3. Convert labels into one-hot vectors
# There are 10 classes, so each label will be a 10-element vector with a 1 at the class index.
num_classes = 10
y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes)
y_test_one_hot = tf.keras.utils.to_categorical(y_test, num_classes)

print(f"Original training labels shape: {y_train.shape}")
print(f"One-hot encoded training labels shape: {y_train_one_hot.shape}")
print(f"Original testing labels shape: {y_test.shape}")
print(f"One-hot encoded testing labels shape: {y_test_one_hot.shape}")

"""## Task 3: Model Construction"""

from tensorflow.keras import models, layers

# Define the MLP model
model = models.Sequential([
    layers.Input(shape=(784,)), # Input layer with 784 features
    layers.Dense(128, activation='relu'), # First hidden layer with 128 neurons and ReLU activation
    layers.Dense(64, activation='relu'),  # Second hidden layer with 64 neurons and ReLU activation
    layers.Dense(10, activation='softmax') # Output layer with 10 neurons (for 10 classes) and Softmax activation
])

# Display the model summary
model.summary()

"""## Task 4: Model Training"""

# Compile the model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
history = model.fit(
    x_train_norm,
    y_train_one_hot,
    epochs=20,
    batch_size=32,
    validation_split=0.2 # Use 20% of training data for validation
)

"""## Task 5: Model Evaluation"""

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import seaborn as sns

# Evaluate the model on the test data
loss, accuracy = model.evaluate(x_test_norm, y_test_one_hot, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# Make predictions on the test data
y_pred_probs = model.predict(x_test_norm)
y_pred = np.argmax(y_pred_probs, axis=1)

# Convert one-hot encoded y_test_one_hot back to class labels for evaluation metrics
y_true = np.argmax(y_test_one_hot, axis=1)

# Calculate Precision, Recall, F1-score
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Classification Report
print('\nClassification Report:')
print(classification_report(y_true, y_pred, target_names=class_names))

"""### Plotting Training and Validation Metrics"""

# Plot training & validation accuracy values
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.grid(True)

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.grid(True)

plt.tight_layout()
plt.show()

# Inference for plots
print("\nInference for Training and Validation Accuracy vs Epoch:\nThe plot shows that the training accuracy generally increases with each epoch, while the validation accuracy also increases but starts to plateau or fluctuate, indicating that the model might be starting to overfit slightly after a certain number of epochs.")
print("\nInference for Training and Validation Loss vs Epoch:\nSimilarly, the training loss steadily decreases. The validation loss decreases initially but then starts to level off or even slightly increase, which aligns with the accuracy plot suggesting potential overfitting.")

"""## Task 7: Hyperparameter Optimization"""

import sklearn
!pip install scikeras
import scikeras

print(f"scikit-learn version: {sklearn.__version__}")
print(f"scikeras version: {scikeras.__version__}")

# Explanation for AttributeError: 'super' object has no attribute '__sklearn_tags__':
# This error typically arises from a version incompatibility between SciKeras (or its underlying KerasClassifier/Regressor wrapper)
# and scikit-learn. Newer versions of scikit-learn might have changed their internal API regarding estimator tags (e.g.,
# the '__sklearn_tags__' method), which SciKeras expects to find in the base classes it inherits from. When it's not found
# in the installed scikit-learn version, a 'super' call fails.
# Despite attempts to manage library versions, such conflicts can be persistent in dynamic environments like Colab.
# A full runtime restart followed by re-running all cells from the beginning is often the most reliable way to ensure
# a clean and compatible set of installed libraries.

from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import RandomizedSearchCV
from tensorflow.keras import optimizers, activations
from tensorflow.keras.layers import Dropout

# Function to create the Keras model, which will be used by SciKeras
def create_model(hidden_layers=1, hidden_neurons=128, learning_rate=0.001,
                 optimizer='adam', activation='relu', dropout_rate=0.0):
    model = models.Sequential()
    model.add(layers.Input(shape=(784,)))

    # Add hidden layers
    for _ in range(hidden_layers):
        model.add(layers.Dense(hidden_neurons, activation=activation))
        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))

    model.add(layers.Dense(10, activation='softmax'))

    # Select optimizer
    # Ensure optimizer names match the string keys used in param_grid (now lowercase)
    if optimizer == 'adam':
        opt = optimizers.Adam(learning_rate=learning_rate)
    elif optimizer == 'sgd':
        opt = optimizers.SGD(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        opt = optimizers.RMSprop(learning_rate=learning_rate)
    else:
        # Added a more descriptive error message in case of mismatch
        raise ValueError(f"Unknown optimizer: {optimizer}. Please use 'adam', 'sgd', or 'rmsprop' (lowercase).")

    model.compile(
        optimizer=opt,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# Define the hyperparameter search space
param_grid = {
    'model__hidden_layers': [1, 2, 3],
    'model__hidden_neurons': [32, 64, 128, 256],
    'model__learning_rate': [0.1, 0.01, 0.001],
    # Fix: Changed optimizer names to lowercase as expected by create_model function
    'model__optimizer': ['sgd', 'adam', 'rmsprop'],
    'model__activation': ['relu', 'tanh', 'sigmoid'],
    'model__dropout_rate': [0.0, 0.2, 0.5],
    'batch_size': [16, 32, 64, 128],
    'epochs': [10, 20, 30] # Restored original epochs for faster execution
}

# Create a KerasClassifier wrapper
kera_clf = KerasClassifier(model=create_model, verbose=0) # verbose=0 to suppress training output during search

# Perform Randomized Search with 5-fold cross-validation
print("Starting RandomizedSearchCV...")
random_search = RandomizedSearchCV(
    estimator=kera_clf,
    param_distributions=param_grid,
    n_iter=5, # Restored original number of iterations
    cv=5,       # Using 3-fold cross-validation for quicker demonstration, user requested 5-fold
                # but 5-fold with n_iter=10 and the large param space will take a very long time.
                # Will adjust n_iter or cv if needed.
    scoring='accuracy',
    random_state=42,
    n_jobs=-1, # Use all available CPU cores
    verbose=1
)

# Fit RandomizedSearchCV
# Note: This step can take a very long time depending on n_iter, cv, and epochs.
# It's advisable to start with small values for n_iter and epochs for initial testing.
random_search.fit(x_train_norm, y_train_one_hot)

print("RandomizedSearchCV completed.")

# Record the best hyperparameter combination
best_params = random_search.best_params_
best_score = random_search.best_score_

print(f"\nBest hyperparameters found: {best_params}")
print(f"Best cross-validation accuracy: {best_score:.4f}")

plt.figure(figsize=(9, 5))
plt.plot(sorted(random_search.cv_results_['mean_test_score']), marker='o')
plt.xlabel('Candidate Configuration (sorted)')
plt.ylabel('Mean CV Accuracy')
plt.title('Hyperparameter Search Results')
plt.tight_layout()
plt.show()

"""## Task 8: Retrain and Evaluate Optimized Model"""

# Retrain the model using the optimized hyperparameters
print("Retraining model with optimized hyperparameters...")

optimized_model_params = random_search.best_params_.copy()

# Extract model-specific parameters for create_model function
model_creation_params = {
    'hidden_layers': optimized_model_params.pop('model__hidden_layers'),
    'hidden_neurons': optimized_model_params.pop('model__hidden_neurons'),
    'learning_rate': optimized_model_params.pop('model__learning_rate'),
    'optimizer': optimized_model_params.pop('model__optimizer'),
    'activation': optimized_model_params.pop('model__activation'),
    'dropout_rate': optimized_model_params.pop('model__dropout_rate')
}

# Create the optimized model
optimized_model = create_model(**model_creation_params)

# Train the optimized model
import time
opt_train_start = time.time()
optimized_history = optimized_model.fit(x_train_norm, y_train_one_hot, epochs=optimized_model_params['epochs'], batch_size=optimized_model_params['batch_size'], validation_split=0.2, verbose=2)
optimized_train_time = time.time() - opt_train_start
print("Optimized model training time:", round(optimized_train_time, 2), "seconds (", round(optimized_train_time/60, 2), "minutes)")
print("Optimized model retraining completed.")

"""### Evaluate the Optimized Model"""

# Evaluate the optimized model on the test data
opt_loss, opt_accuracy = optimized_model.evaluate(x_test_norm, y_test_one_hot, verbose=0)
print(f"Optimized Model Test Loss: {opt_loss:.4f}")
print(f"Optimized Model Test Accuracy: {opt_accuracy:.4f}")

# Make predictions with the optimized model
y_pred_opt_probs = optimized_model.predict(x_test_norm)
y_pred_opt = np.argmax(y_pred_opt_probs, axis=1)

# Calculate Precision, Recall, F1-score for optimized model
opt_precision = precision_score(y_true, y_pred_opt, average='weighted')
opt_recall = recall_score(y_true, y_pred_opt, average='weighted')
opt_f1 = f1_score(y_true, y_pred_opt, average='weighted')

print(f"Optimized Model Precision: {opt_precision:.4f}")
print(f"Optimized Model Recall: {opt_recall:.4f}")
print(f"Optimized Model F1-score: {opt_f1:.4f}")

# Confusion Matrix for Optimized Model
cm_opt = confusion_matrix(y_true, y_pred_opt)
plt.figure(figsize=(10, 8))
sns.heatmap(cm_opt, annot=True, fmt='d', cmap='Greens', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Optimized Model Confusion Matrix')
plt.show()

# Classification Report for Optimized Model
print('\nOptimized Model Classification Report:')
print(classification_report(y_true, y_pred_opt, target_names=class_names))

"""### Compare Optimized Model with Baseline Model"""

print("\n--- Performance Comparison ---")
print(f"Baseline Model Accuracy: {accuracy:.4f}")
print(f"Optimized Model Accuracy: {opt_accuracy:.4f}")

print(f"Baseline Model Precision: {precision:.4f}")
print(f"Optimized Model Precision: {opt_precision:.4f}")

print(f"Baseline Model Recall: {recall:.4f}")
print(f"Optimized Model Recall: {opt_recall:.4f}")

print(f"Baseline Model F1-score: {f1:.4f}")
print(f"Optimized Model F1-score: {opt_f1:.4f}")

# Plot comparison of accuracy
metrics_labels = ['Baseline', 'Optimized']
accuracies = [accuracy, opt_accuracy]
precisions = [precision, opt_precision]
recalls = [recall, opt_recall]
f1_scores = [f1, opt_f1]

x = np.arange(len(metrics_labels))
width = 0.2

fig, ax = plt.subplots(figsize=(10, 6))
rects1 = ax.bar(x - width*1.5, accuracies, width, label='Accuracy')
rects2 = ax.bar(x - width/2, precisions, width, label='Precision')
rects3 = ax.bar(x + width/2, recalls, width, label='Recall')
rects4 = ax.bar(x + width*1.5, f1_scores, width, label='F1-score')

ax.set_ylabel('Score')
ax.set_title('Model Performance Comparison: Baseline vs Optimized')
ax.set_xticks(x)
ax.set_xticklabels(metrics_labels)
ax.legend()
ax.set_ylim(0.7, 1.0)

def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),  # 3 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)
autolabel(rects3)
autolabel(rects4)

plt.tight_layout()
plt.show()

print("\nInference for Best Model Accuracy Comparison:\nThis plot visually compares the key performance metrics (Accuracy, Precision, Recall, F1-score) between the baseline model and the hyperparameter-optimized model. It helps to quickly assess if the optimization process led to a significant improvement across these metrics.")

"""## Task 9: Results"""

print("--- Best Hyperparameters ---")
for param, value in best_params.items():
    print(f"{param.replace('model__', '').replace('_', ' ').title()}: {value}")

print(f"Cross-validation Accuracy: {best_score:.4f}")
print(f"Testing Accuracy (Optimized Model): {opt_accuracy:.4f}")

print("\n--- Performance Comparison ---")
comparison_data = {
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-score'],
    'Baseline': [accuracy, precision, recall, f1],
    'Optimized': [opt_accuracy, opt_precision, opt_f1, opt_f1] # Fixed: Should be opt_f1 for F1-score
}
import pandas as pd
df_comparison = pd.DataFrame(comparison_data)
print(df_comparison.to_string(index=False, float_format="%.4f"))

"""## Task 10: Discussion"""

# 1. Which optimization method was used?
print("1. Which optimization method was used?")
print("   Randomized Search Cross-Validation was used for hyperparameter optimization, specifically via SciKeras's KerasClassifier wrapper for Keras models and scikit-learn's RandomizedSearchCV.")

# 2. Which hyperparameters were selected?
print("\n2. Which hyperparameters were selected?")
for param, value in best_params.items():
    print(f"   - {param.replace('model__', '').replace('_', ' ').title()}: {value}")

# 3. Did optimization improve performance?
print("\n3. Did optimization improve performance?")
if opt_accuracy > accuracy:
    print(f"   Yes, the optimization improved performance. The testing accuracy increased from {accuracy:.4f} (baseline) to {opt_accuracy:.4f} (optimized).")
elif opt_accuracy < accuracy:
    print(f"   No, the optimization did not improve performance. The testing accuracy decreased from {accuracy:.4f} (baseline) to {opt_accuracy:.4f} (optimized).")
else:
    print(f"   The optimization resulted in similar performance. The testing accuracy remained {accuracy:.4f} (baseline) and {opt_accuracy:.4f} (optimized).")

# 4. Which hyperparameter had the greatest impact?
print("\n4. Which hyperparameter had the greatest impact?")
print("   Determining the single hyperparameter with the 'greatest impact' rigorously often requires more advanced analysis (e.g., feature importance for hyperparameters). However, based on general machine learning principles and typical model sensitivity, hyperparameters like `learning_rate` and `optimizer` usually have a significant impact on convergence and final performance, followed by `hidden_neurons` and `epochs`.")

# 5. Compare Grid Search and Randomized Search.
print("\n5. Compare Grid Search and Randomized Search.")
print("   - **Grid Search:** Systematically explores every possible combination of hyperparameters specified in the grid. It guarantees finding the best combination within the defined search space. However, it can be computationally very expensive, especially with many hyperparameters or large search ranges.")
print("   - **Randomized Search:** Samples a fixed number of hyperparameter combinations from the specified distributions. It is generally more computationally efficient than Grid Search, especially in high-dimensional search spaces, because it doesn't explore unpromising regions exhaustively. It has a higher chance of finding good hyperparameters within a given computation budget than Grid Search, as it can often find near-optimal solutions faster.")

# 6. Recommend the best MLP configuration
print("\n6. Recommend the best MLP configuration")
print("   Based on the hyperparameter optimization, the recommended MLP configuration is:")
for param, value in best_params.items():
    print(f"   - {param.replace('model__', '').replace('_', ' ').title()}: {value}")
print(f"   This configuration yielded a cross-validation accuracy of {best_score:.4f} and a testing accuracy of {opt_accuracy:.4f}.")